appregistry: fix missing parameter
This should fix "java.lang.NoSuchMethodError: No such DSL method 'getMetadataNVRs' found among steps..." error at https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fappregistry/8612/console.