promote-assembly: Fix missing variable error
Fixes `hudson.remoting.ProxyException:
groovy.lang.MissingPropertyException: No such property: release_name for
class: WorkflowScript`.

Adds comment for variable `release_info`.