prepare-release: Fix INCLUDE_SHIPPED parameter prepare-release: fix INCLUDE_SHIPPED
```
Error: No such option: --include_shipped Did you mean --include-shipped?
```

The flag should be --include-shipped instead of --include_shipped.