fix broken ocp3 job: No such property: GITHUB_BASE
https://saml.buildvm.openshift.eng.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Focp3/167/:
groovy.lang.MissingPropertyException: No such property: GITHUB_BASE for class: Script1

This is because buildlib requires `GITHUB_BASE` global variable to be present.