Expect None `tag_res` on signed-compose job
This week I got several signed-compose job failures because `tag_res` was `None`:

```
Traceback (most recent call last):
  File "./ocp-tag-signed-errata-builds.py", line 389, in <module>
Waiting for task 28376015 to finish
.
    main()
  File "./ocp-tag-signed-errata-builds.py", line 385, in main
    tag_builds(koji_proxy, opts.brew_pending_tag, missing, tagged_builds, test=opts.test)
  File "./ocp-tag-signed-errata-builds.py", line 75, in tag_builds
    if 'faultCode' in tag_res:
TypeError: argument of type 'NoneType' is not iterable

----------------------------------------

Finished: FAILURE
```